[character]
success_symbol = "[✅](bold green)"
error_symbol = "[❌](bold red)"

[username]
style_user = "bold dimmed blue"
show_always = true

# Use custom format
format = """
[](bold blue)
[](bold blue)$username """

# Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false
